import type { MarkerData } from '~/types/marker'

const markers: MarkerData[] = [
  {
    id: '1',
    name: 'Hanoi Old Quarter Hotel',
    description: 'A charming boutique hotel nestled in the heart of Hanoi\'s historic Old Quarter, steps from Hoan Kiem Lake.',
    image: 'https://placehold.co/600x400?text=Hanoi+Old+Quarter+Hotel',
    lat: 21.0285,
    lng: 105.8542,
    actionLabel: 'View Details',
    actionUrl: '#',
  },
  {
    id: '2',
    name: 'Hoan Kiem Lake',
    description: 'The iconic lake at the center of Hanoi, home to the historic Turtle Tower and Ngoc Son Temple.',
    image: 'https://placehold.co/600x400?text=Hoan+Kiem+Lake',
    lat: 21.0288,
    lng: 105.8525,
    actionLabel: 'View Details',
    actionUrl: '#',
  },
  {
    id: '3',
    name: 'Ha Long Bay Cruise Terminal',
    description: 'Departure point for scenic cruises through the UNESCO World Heritage limestone karsts of Ha Long Bay.',
    image: 'https://placehold.co/600x400?text=Ha+Long+Bay+Cruise',
    lat: 20.9517,
    lng: 107.0748,
    actionLabel: 'View Details',
    actionUrl: '#',
  },
  {
    id: '4',
    name: 'Da Nang Beach Resort',
    description: 'A luxury beachfront resort along My Khe Beach, known for its white sand and clear blue waters.',
    image: 'https://placehold.co/600x400?text=Da+Nang+Beach+Resort',
    lat: 16.0544,
    lng: 108.2022,
    actionLabel: 'View Details',
    actionUrl: '#',
  },
  {
    id: '5',
    name: 'Hoi An Ancient Town',
    description: 'A beautifully preserved trading port from the 15th-19th centuries, famous for lantern-lit streets and tailors.',
    image: 'https://placehold.co/600x400?text=Hoi+An+Ancient+Town',
    lat: 15.8801,
    lng: 108.3380,
    actionLabel: 'View Details',
    actionUrl: '#',
  },
  {
    id: '6',
    name: 'Hue Imperial Citadel',
    description: 'The walled fortress and palace complex of the Nguyen Dynasty emperors, a UNESCO World Heritage Site.',
    image: 'https://placehold.co/600x400?text=Hue+Imperial+Citadel',
    lat: 16.4698,
    lng: 107.5796,
    actionLabel: 'View Details',
    actionUrl: '#',
  },
  {
    id: '7',
    name: 'Ho Chi Minh City Riverside Hotel',
    description: 'Modern riverside hotel with panoramic views of the Saigon River and District 1 skyline.',
    image: 'https://placehold.co/600x400?text=HCMC+Riverside+Hotel',
    lat: 10.7769,
    lng: 106.7009,
    actionLabel: 'View Details',
    actionUrl: '#',
  },
  {
    id: '8',
    name: 'Ben Thanh Market',
    description: 'Saigon\'s most iconic market, offering everything from local street food to souvenirs and textiles.',
    image: 'https://placehold.co/600x400?text=Ben+Thanh+Market',
    lat: 10.7725,
    lng: 106.6980,
    actionLabel: 'View Details',
    actionUrl: '#',
  },
  {
    id: '9',
    name: 'Mekong River Tour Base',
    description: 'Starting point for boat tours through the Mekong Delta, exploring floating markets and coconut villages.',
    image: 'https://placehold.co/600x400?text=Mekong+River+Tour',
    lat: 10.0452,
    lng: 105.7469,
    actionLabel: 'View Details',
    actionUrl: '#',
  },
  {
    id: '10',
    name: 'Nha Trang Beach Hotel',
    description: 'Coastal resort hotel on Nha Trang Bay, offering diving excursions and beachfront dining.',
    image: 'https://placehold.co/600x400?text=Nha+Trang+Beach+Hotel',
    lat: 12.2388,
    lng: 109.1967,
    actionLabel: 'View Details',
    actionUrl: '#',
  },
]

export function useMarkerData(): MarkerData[] {
  return markers
}
